//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDRSharp.Rtl_433.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDRSharp.Rtl_433.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want import devices list.
        /// </summary>
        internal static string ClassFormDevicesList_import_devices_list {
            get {
                return ResourceManager.GetString("ClassFormDevicesList_import_devices_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import devices list.
        /// </summary>
        internal static string ClassFormDevicesList_Import_devices_list_1 {
            get {
                return ResourceManager.GetString("ClassFormDevicesList_Import_devices_list_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file.
        /// </summary>
        internal static string ClassFormDevicesList_The_file_ {
            get {
                return ResourceManager.GetString("ClassFormDevicesList_The_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error create folder Recordings to folder SDRSharp.
        /// </summary>
        internal static string ClassFormDevicesLists_to_folder_SDRSharp {
            get {
                return ResourceManager.GetString("ClassFormDevicesLists_to_folder_SDRSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is to SDRSharp folder.
        /// </summary>
        internal static string ClassFormDevicesLists_to_SDRSharp_folder {
            get {
                return ResourceManager.GetString("ClassFormDevicesLists_to_SDRSharp_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error export item fct(serializeText).File:.
        /// </summary>
        internal static string ClassFunctionsVirtuaserializeText__File_ {
            get {
                return ResourceManager.GetString("ClassFunctionsVirtuaserializeText__File_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown modulation.
        /// </summary>
        internal static string ClassInterfaceWithRt3_unknown_modulation {
            get {
                return ResourceManager.GetString("ClassInterfaceWithRt3_unknown_modulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error ptrInfosToPlugin.
        /// </summary>
        internal static string ClassInterfaceWithRtror_ptrInfosToPlugin {
            get {
                return ResourceManager.GetString("ClassInterfaceWithRtror_ptrInfosToPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AlwaysOnTop.
        /// </summary>
        internal static string ClassTitleBarre_AlwaysOnTop {
            get {
                return ResourceManager.GetString("ClassTitleBarre_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        internal static string ClassTitleBarre_Langue {
            get {
                return ResourceManager.GetString("ClassTitleBarre_Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error create folder.
        /// </summary>
        internal static string ClassUtils_Error_create_folder_ {
            get {
                return ResourceManager.GetString("ClassUtils_Error_create_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Initialize.
        /// </summary>
        internal static string ClassUtils_Error_Initialize {
            get {
                return ResourceManager.GetString("ClassUtils_Error_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à genere file test wav -127 to 128.
        /// </summary>
        internal static string ClassUtils_genere_fi_test_wav_127_to_128 {
            get {
                return ResourceManager.GetString("ClassUtils_genere_fi_test_wav_127_to_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à test.
        /// </summary>
        internal static string ClassUtils_test {
            get {
                return ResourceManager.GetString("ClassUtils_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} (Messages received : {1}/{2}).
        /// </summary>
        internal static string ClassVirtualListViews_received___1___2__ {
            get {
                return ResourceManager.GetString("ClassVirtualListViews_received__{1}_{2}_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel record.
        /// </summary>
        internal static string FormDevices_Cancel_record {
            get {
                return ResourceManager.GetString("FormDevices_Cancel_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data {0}.
        /// </summary>
        internal static string FormDevices_Data__0_ {
            get {
                return ResourceManager.GetString("FormDevices_Data_{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error fct(listViewListMessages_RetrieveVirtualItem).
        /// </summary>
        internal static string FormDevices_Error_fcRetrieveVirtualItem_ {
            get {
                return ResourceManager.GetString("FormDevices_Error_fcRetrieveVirtualItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Freeze graphs.
        /// </summary>
        internal static string FormDevices_Freeze_graphs {
            get {
                return ResourceManager.GetString("FormDevices_Freeze_graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        internal static string FormDevices_Info {
            get {
                return ResourceManager.GetString("FormDevices_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NB messages: {0}.
        /// </summary>
        internal static string FormDevices_NB_messages___0_ {
            get {
                return ResourceManager.GetString("FormDevices_NB_messages__{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NB messages: 0.
        /// </summary>
        internal static string FormDevices_NB_messages__0 {
            get {
                return ResourceManager.GetString("FormDevices_NB_messages__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data for the graph.
        /// </summary>
        internal static string FormDevices_No_data_for_the_graph {
            get {
                return ResourceManager.GetString("FormDevices_No_data_for_the_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Period: 0.
        /// </summary>
        internal static string FormDevices_Period__0 {
            get {
                return ResourceManager.GetString("FormDevices_Period__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Period:{0}s..
        /// </summary>
        internal static string FormDevices_Period__0_s_ {
            get {
                return ResourceManager.GetString("FormDevices_Period_{0}s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Period max: 0.
        /// </summary>
        internal static string FormDevices_Period_max__0 {
            get {
                return ResourceManager.GetString("FormDevices_Period_max__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Period max:{0}s..
        /// </summary>
        internal static string FormDevices_Period_max__0_s_ {
            get {
                return ResourceManager.GetString("FormDevices_Period_max_{0}s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record data buffer Wav (checkbox on panel).
        /// </summary>
        internal static string FormDevices_Record_dv_checkbox_on_panel_ {
            get {
                return ResourceManager.GetString("FormDevices_Record_dv_checkbox_on_panel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh data.
        /// </summary>
        internal static string FormDevices_Refresh_data {
            get {
                return ResourceManager.GetString("FormDevices_Refresh_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save only once.
        /// </summary>
        internal static string FormDevices_Save_only_once {
            get {
                return ResourceManager.GetString("FormDevices_Save_only_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to directory Recordings.
        /// </summary>
        internal static string FormDevices_to_directory_Recordings {
            get {
                return ResourceManager.GetString("FormDevices_to_directory_Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use mouse wheel for zoom.
        /// </summary>
        internal static string FormDevices_Use_mouse_wheel_for_zoom {
            get {
                return ResourceManager.GetString("FormDevices_Use_mouse_wheel_for_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait to receive new data.
        /// </summary>
        internal static string FormDevices_Wait_to_receive_new_data {
            get {
                return ResourceManager.GetString("FormDevices_Wait_to_receive_new_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can replay Stereo file with SdrSharp Source=Baseband File player.
        /// </summary>
        internal static string FormDevices_You_can_Baseband_File_player {
            get {
                return ResourceManager.GetString("FormDevices_You_can_Baseband_File_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Messages received :.
        /// </summary>
        internal static string FormDevicesListMessa_Messages_received__ {
            get {
                return ResourceManager.GetString("FormDevicesListMessa_Messages_received__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to directory Recordings.
        /// </summary>
        internal static string FormDevicesListMessadirectory_Recordings {
            get {
                return ResourceManager.GetString("FormDevicesListMessadirectory_Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can reload file with Calc.
        /// </summary>
        internal static string FormDevicesListMessaeload_file_with_Calc {
            get {
                return ResourceManager.GetString("FormDevicesListMessaeload_file_with_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export data (.txt).
        /// </summary>
        internal static string FormDevicesListMessaes_Export_data__txt_ {
            get {
                return ResourceManager.GetString("FormDevicesListMessaes_Export_data__txt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Messages received : 0).
        /// </summary>
        internal static string FormDevicesListMessaessages_received__0_ {
            get {
                return ResourceManager.GetString("FormDevicesListMessaessages_received__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export--&gt;.
        /// </summary>
        internal static string FormDevicesListMessages_Export___ {
            get {
                return ResourceManager.GetString("FormDevicesListMessages_Export___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° Mes..
        /// </summary>
        internal static string FormDevicesListMessages_N__Mes_ {
            get {
                return ResourceManager.GetString("FormDevicesListMessages_N__Mes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record data.
        /// </summary>
        internal static string FormDevicesListMessages_Record_data {
            get {
                return ResourceManager.GetString("FormDevicesListMessages_Record_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à name file = title window+date.txt.
        /// </summary>
        internal static string FormDevicesListMessaitle_window_date_txt {
            get {
                return ResourceManager.GetString("FormDevicesListMessaitle_window_date_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error fct(listViewListMessages_RetrieveVirtualItem).
        /// </summary>
        internal static string FormDevicesListMessaRetrieveVirtualItem_ {
            get {
                return ResourceManager.GetString("FormDevicesListMessaRetrieveVirtualItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export messages OK.
        /// </summary>
        internal static string FormDevicesListMessas_Export_messages_OK {
            get {
                return ResourceManager.GetString("FormDevicesListMessas_Export_messages_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close form list devices.
        /// </summary>
        internal static string FormListDevices_Close_form_list_devices_ {
            get {
                return ResourceManager.GetString("FormListDevices_Close_form_list_devices_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column:.
        /// </summary>
        internal static string FormListDevices_Column_ {
            get {
                return ResourceManager.GetString("FormListDevices_Column_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devices received :.
        /// </summary>
        internal static string FormListDevices_Devices_received__ {
            get {
                return ResourceManager.GetString("FormListDevices_Devices_received__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devices received : 0.
        /// </summary>
        internal static string FormListDevices_Devices_received__0 {
            get {
                return ResourceManager.GetString("FormListDevices_Devices_received__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want export devices list?(.
        /// </summary>
        internal static string FormListDevices_Do_yexport_devices_list_ {
            get {
                return ResourceManager.GetString("FormListDevices_Do_yexport_devices_list_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à empty.
        /// </summary>
        internal static string FormListDevices_empty {
            get {
                return ResourceManager.GetString("FormListDevices_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error fct(listDevices_RetrieveVirtualItem).
        /// </summary>
        internal static string FormListDevices_ErroRetrieveVirtualItem_ {
            get {
                return ResourceManager.GetString("FormListDevices_ErroRetrieveVirtualItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error import devices fct(deSerializeText).File:.
        /// </summary>
        internal static string FormListDevices_ErroSerializeText__File_ {
            get {
                return ResourceManager.GetString("FormListDevices_ErroSerializeText__File_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export devices list.
        /// </summary>
        internal static string FormListDevices_Export_devices_list {
            get {
                return ResourceManager.GetString("FormListDevices_Export_devices_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File :.
        /// </summary>
        internal static string FormListDevices_File_ {
            get {
                return ResourceManager.GetString("FormListDevices_File_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import devices File.
        /// </summary>
        internal static string FormListDevices_Import_devices_File {
            get {
                return ResourceManager.GetString("FormListDevices_Import_devices_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop plugin or change form type before close..
        /// </summary>
        internal static string FormListDevices_Stopm_type_before_close_ {
            get {
                return ResourceManager.GetString("FormListDevices_Stopm_type_before_close_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -AGC:on(corresponds to auto gain with rtl433) can be manually-&gt;off..
        /// </summary>
        internal static string Rtl_433_Panel___AGC_an_be_manually__off_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___AGC_an_be_manually__off_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -Check frequency.
        /// </summary>
        internal static string Rtl_433_Panel___Check_frequency {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___Check_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        internal static string Rtl_433_Panel___Clear {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -RTL AGC:on.(not the AGC panel) can be set off if good signals..
        /// </summary>
        internal static string Rtl_433_Panel___RTL_off_if_good_signals_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___RTL_off_if_good_signals_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -Sampling mode-&gt;quadrature sampling.
        /// </summary>
        internal static string Rtl_433_Panel___Samp_quadrature_sampling {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___Samp_quadrature_sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -Sample Rate-&gt;0.25 MSPS or more for certain devices FSK or f &gt; 433Mhz....
        /// </summary>
        internal static string Rtl_433_Panel___Samps_FSK_or_f__433Mhz__ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel___Samps_FSK_or_f__433Mhz__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All to.
        /// </summary>
        internal static string Rtl_433_Panel__All_to {
            get {
                return ResourceManager.GetString("Rtl_433_Panel__All_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Rtl_433_Panel_Cancel {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clipboard.
        /// </summary>
        internal static string Rtl_433_Panel_clipboard {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console RTL_433--- Line = .
        /// </summary>
        internal static string Rtl_433_Panel_Console_RTL_433___Ligne__ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Console_RTL_433___Ligne__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console RTL_433---nbLigne=.
        /// </summary>
        internal static string Rtl_433_Panel_Console_RTL_433__nbLigne_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Console_RTL_433__nbLigne_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .cu8 to .wav.
        /// </summary>
        internal static string Rtl_433_Panel_cu8_to_wav {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_cu8_to_wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled plugin.
        /// </summary>
        internal static string Rtl_433_Panel_Disabled_plugin {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Disabled_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        internal static string Rtl_433_Panel_Display {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled plugin.
        /// </summary>
        internal static string Rtl_433_Panel_Enabled_plugin {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Enabled_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled plugin (.
        /// </summary>
        internal static string Rtl_433_Panel_Enabled_plugin_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Enabled_plugin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error fct(listViewConsole_RetrieveVirtualItem).
        /// </summary>
        internal static string Rtl_433_Panel_Error_RetrieveVirtualItem_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Error_RetrieveVirtualItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free.
        /// </summary>
        internal static string Rtl_433_Panel_Free {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequency.
        /// </summary>
        internal static string Rtl_433_Panel_Frequency {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequency (Hz).
        /// </summary>
        internal static string Rtl_433_Panel_Frequency_Hz_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Frequency_Hz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphiques.
        /// </summary>
        internal static string Rtl_433_Panel_Graphiques {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Graphiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide select.
        /// </summary>
        internal static string Rtl_433_Panel_Hide_select {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Hide_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à if necessary you can increase it in SDRSharp.config(key RTL_433_plugin.maxLinesConsole).
        /// </summary>
        internal static string Rtl_433_Panel_if_necgin_maxLinesConsole_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_if_necgin_maxLinesConsole_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If Orange:F&lt;300Mhz or F&gt;1000Mhz..
        /// </summary>
        internal static string Rtl_433_Panel_If_Ora300Mhz_or_F_1000Mhz_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_If_Ora300Mhz_or_F_1000Mhz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List devices.
        /// </summary>
        internal static string Rtl_433_Panel_List_devices {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_List_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List messages.
        /// </summary>
        internal static string Rtl_433_Panel_List_messages {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_List_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messages.
        /// </summary>
        internal static string Rtl_433_Panel_Messages {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No sample rate detected in the file name: _sample rate+k.
        /// </summary>
        internal static string Rtl_433_Panel_No_samname__sample_rate_k_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_No_samname__sample_rate_k_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ok files.
        /// </summary>
        internal static string Rtl_433_Panel_ok_files {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_ok_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters configure source.
        /// </summary>
        internal static string Rtl_433_Panel_Parameers_configure_source {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Parameers_configure_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        internal static string Rtl_433_Panel_Parameter {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red if Time cycle &gt; 1000ms., you risk losing messages(not if source=file).
        /// </summary>
        internal static string Rtl_433_Panel_Red_if_not_if_source_file_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Red_if_not_if_source_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sample rate.
        /// </summary>
        internal static string Rtl_433_Panel_Sample_Rate_s {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Sample_Rate_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection to.
        /// </summary>
        internal static string Rtl_433_Panel_Select_to {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Select_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show select.
        /// </summary>
        internal static string Rtl_433_Panel_Show_select {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Show_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch.
        /// </summary>
        internal static string Rtl_433_Panel_Start {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start once to fill the devices list.
        /// </summary>
        internal static string Rtl_433_Panel_Start_ill_the_devices_list {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Start_ill_the_devices_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string Rtl_433_Panel_Stop {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time display:.
        /// </summary>
        internal static string Rtl_433_Panel_Time_display_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Time_display_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translate cu8 to wav.
        /// </summary>
        internal static string Rtl_433_Panel_Translate_cu8_to_wav {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Translate_cu8_to_wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translate is completed.
        /// </summary>
        internal static string Rtl_433_Panel_Translate_is_completed {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Translate_is_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translate is NOT completed.
        /// </summary>
        internal static string Rtl_433_Panel_Translte_is_NOT_completed_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Translte_is_NOT_completed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version de test.
        /// </summary>
        internal static string Rtl_433_Panel_Version_de_test {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Version_de_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait.
        /// </summary>
        internal static string Rtl_433_Panel_Wait {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait Radio.
        /// </summary>
        internal static string Rtl_433_Panel_Wait_Radio {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_Wait_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reached the maximum number of rows provided in the console(.
        /// </summary>
        internal static string Rtl_433_Panel_You_haided_in_the_console_ {
            get {
                return ResourceManager.GetString("Rtl_433_Panel_You_haided_in_the_console_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialize RTL_433_plugin.
        /// </summary>
        internal static string Rtl_433_Plugin__Initalize_RTL_433_plugin {
            get {
                return ResourceManager.GetString("Rtl_433_Plugin__Initalize_RTL_433_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Initialize.
        /// </summary>
        internal static string Rtl_433_Plugin_Error_Initialize {
            get {
                return ResourceManager.GetString("Rtl_433_Plugin_Error_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string WavRecorder_Error {
            get {
                return ResourceManager.GetString("WavRecorder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à information.
        /// </summary>
        internal static string WavRecorder_information {
            get {
                return ResourceManager.GetString("WavRecorder_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No record, all values = 0.
        /// </summary>
        internal static string WavRecorder_No_record__all_values__0 {
            get {
                return ResourceManager.GetString("WavRecorder_No_record__all_values__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No record for:.
        /// </summary>
        internal static string WavRecorder_No_record_for_ {
            get {
                return ResourceManager.GetString("WavRecorder_No_record_for_", resourceCulture);
            }
        }
    }
}
