name: Build All

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version manuelle (laisser vide pour auto-incrément)"
        required: false
      notes:
        description: "Notes de release"
        required: false

jobs:
  build:
    runs-on: windows-latest
    # ---------------------------------------------------------
    # 3) Get last tag
    # ---------------------------------------------------------
    steps:
    - name: Get last tag
      id: lasttag
      shell: pwsh
      run: |
        echo "LAST_TAG=0.0.0.100" >> $env:GITHUB_ENV
        Write-Host "Dernier tag trouvé : 0.0.0.100"
