name: Build plugin DLL

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-plugin]

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ CI_x86, CI_x64 ]
        include:
          - config: CI_x86
            platform: x86
          - config: CI_x64
            platform: x64

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build plugin (${{ matrix.config }})
        run: msbuild Rtl_433_Plugin/SDRSharp.Rtl_433_Plugin.csproj /p:Configuration=${{ matrix.config }} /p:Platform="${{ matrix.platform }}"

      - name: Upload Rtl_433_Plugin DLL
        uses: actions/upload-artifact@v4
        with:
          name: Rtl_433_Plugin_${{ matrix.platform }}
          path: Rtl_433_Plugin/bin/${{ matrix.platform }}/Release/
